### ISSUE TITLE
Enable UDP support for ZMQ

### ISSUE THREAD

**Issue by miludmann** [orwell-int/server-game#114]
Pls fix

**Comment by massix** [comment]
Fixed in version 8.41 alpha B r 43

**Comment by massix** [comment]
@dchilot can you please verify if the [RARR component](https://www.youtube.com/watch?v=dQw4w9WgXcQ) is still operational after the migration to the NGGYU Protocol v12  for Z or if we have to fallback to v11 ?
@miludmann please don't hesitate to come back to us if the problem persists.

**Comment by dchilot** [comment]
The RARR component is icing the problem like a crazy monkey on a dance-floor. I cannot wait for the upgrade to version 13 of the protocol.

**Comment by massix** [comment]
One does not simply upgrade to v13 of the protocol.
@fdiller we need your help here, when will the v13 be released?

**Comment by massix** [comment]
Reopening the issue because I dislike the big red "CLOSED" label on the top left of the page.
